- MySQLdb/converters.py
> Fix some BLOBs without binary flag is not decoded.

- MySQLdb/converters.py
- MySQLdb/times.py
> Don't use datetime.isoformat() when encoding

- _mysql.c
- tests/test_MySQLdb_nonstandard.py
> Fix _mysql.escape_string()

- MySQLdb/connections.py
- MySQLdb/cursors.py
Fixes #22 (Uncollectable cursor on Python 3.3)
> Remove BaseCursor.__del__

- _mysql.c
- tests/test_MySQLdb_capabilities.py
> Fix UnicodeError when fetching BIT value on Python 3

- README.md
adding require commands for installing python3 development package on Ubuntu and CentOs .
> add install command for python3-dev

- _mysql.c
> Check after mysql_store_result propery

- .travis.yml
travis auto pip cache is disabled if the install command is changed
> cache pip correctly

- MySQLdb/connections.py
- MySQLdb/cursors.py
- tests/test_cursor.py
> Port executemany() implementation from PyMySQL

- .travis.yml
Reverts PyMySQL/mysqlclient-python#61
You don't need this anymore
> Revert "cache pip correctly"

- _mysql.c
> Fix accessing buffer of decrefed string

- _mysql.c
> Use mysql_real_escape_string_quote() if exists

- _mysql.c
> Don't use mysql_real_escape_string_quote on MariaDB

- _mysql.c
- tests/test__mysql.py
> Add typecheck to `_mysql.result()`

- MySQLdb/connections.py
It was too slow on Python ~3.5
> Use surrogateescape normally on Python 3.6

- MySQLdb/cursors.py
Same to https://github.com/PyMySQL/PyMySQL/pull/545
> Allow semicolon at the end of bulk insert query

- MANIFEST.in
GPL-2.0 was removed in b6601fef9efff4786671bb2ecb99ee40d716d1aa
> include LICENSE in source tarball

- _mysql.c
Don't touch MYSQL.reconnect directly.
fixes #176
> Fix compile error with MariaDB 10.2.

- MySQLdb/cursors.py
- tests/test_cursor.py
> Allow bulk insert which no space around `VALUES`

- _mysql.c
> Support error numbers > CR_MAX_ERROR

- _mysql.c
> remove include "my_config.h".

- MySQLdb/connections.py
- MySQLdb/converters.py
- MySQLdb/cursors.py
- _mysql.c
> skip calling converter for some special cases

- _mysql.c
> Fixes MariaDB 10.2.8 version identification

- _mysql.c
> raise InterfaceError when mysql_errno() returns 0

- _mysql.c
In ResultObject_Initialize, always borrow the conv dictionary from the
caller. This simplifies the code, removes an allocation, and fixes ref
leaks in error cases.
> simplify memory management of the conv dictionary

- _mysql.c
They are broken from long ago and making them safe is difficult.
So remove them rather than fix.
> Remove broken row_seek() and row_tell()

- .travis.yml
- tests/test_cursor.py
http://blog.pytest.org/2016/whats-new-in-pytest-30/
https://twitter.com/hashtag/dropthedot
> Use pytest instead of py.test per upstream recommendation, #dropthedot

- setup_posix.py
Fixes #261 
Built with:
Python 3.6.3
MariaDB 10.2.11
python setup.py build --static
> Handle mariadb static library called mariadbclient.a

- _mysql.c
> Add missing checks for connection before calling mysql APIs

- MySQLdb/converters.py
It's suggested in https://github.com/PyMySQL/mysqlclient-python/pull/268#discussion_r225902867.
> Use shorter format for float adapter.

- _mysql.c
nothing special than fixing typo
> Fix typo in _mysql.c

- MySQLdb/cursors.py
- tests/test_MySQLdb_capabilities.py
Recent MySQL versions producec noisy warnings.
And this feature made some difficult bugs in past.
I don't want to maintain this feature anymore.
> Remove automatic warning check

- MySQLdb/_mysql.c
- MySQLdb/cursors.py
> Support field name other than UTF-8

- MySQLdb/cursors.py
- tests/test_cursor.py
> Fix dict parameter support

- MySQLdb/_mysql.c
> use PY_SSIZE_T_CLEAN

- setup_posix.py
> try mariadb_config when mysql_config is not found

- .travis.yml
Travis doesn't run since :
https://github.com/PyMySQL/mysqlclient-python/commit/a8329a3096596d65ff9ab26cdd579b1d1ca3a0af
Try to fix it
> [CI] Fix travis build

- .travis.yml
> py38 is now official

- setup_posix.py
> Remove -lcrypto -lssl -lz in non static build

- MySQLdb/connections.py
- tests/test_MySQLdb_nonstandard.py
> Add Context Manager Interface to Connection.

- MySQLdb/cursors.py
> Fix simple typo: stetement -> statement

- setup_posix.py
> Add "-std=c99" to cflags implicitly

- .github/workflows/windows.yaml
> Update windows build workflow

- .github/workflows/django.yaml
Django 3.2 LTS will be supported until 2024-04.
> Update Django test workflow

- setup.py
> Support pkg-config libmariadb

- .github/workflows/tests.yaml
- pyproject.toml
This PR adds Python 3.12 to test matrix.
> chore(python): add Python 3.12 in test matrix

- src/MySQLdb/_mysql.c
> Support MySQL 8.3

- doc/user_guide.rst
> doc: add link to README
