doc/FAQ.rst
doc/user_guide.rst
metadata.cfg

Update PEP 249 URL

---

MySQLdb/cursors.py

Fix SSCursor is not iterator on Python 3

---

_mysql.c

missing default value: raise IntegrityError instead of OperationalError
Follow Python DB API 2.0:
http://legacy.python.org/dev/peps/pep-0249/#integrityerror
Initially reported here:
https://sourceforge.net/p/mysql-python/bugs/336/

missing default value: raise IntegrityError

---

MySQLdb/connections.py

`atoi` is deprecated since python 2.0 and not in python 3. I guess this code is not being run since `_mysql.c` looks like it always defines `warning_count` anyway, but it should not sit around being python-3-incompatible.

connections.py use int not atoi

---

MySQLdb/cursors.py

`BaseCursor.errorhandler` is removed after cursor is closed. This resolves #37.

Raise `ProgrammingError` properly when connection is closed

---

.gitignore
MySQLdb/times.py
tests/test_MySQLdb_times.py
tox.ini

This adds close to 100% coverage for `MySQLdb.times`. We're experience a lot of our request time spent in this module and this is the first step of trying to optimize its performance.

Add tests for times module

---

MySQLdb/times.py
tests/test_MySQLdb_times.py

Results from best of three runs with 1 million calls:
```python
OLD '2038-01-19': 3.150
NEW '2038-01-19': 2.509
OLD '2038-01-19 12:13:14': 6.807
NEW '2038-01-19 12:13:14': 4.613
OLD '2038-01-19 12:13:14.123': 7.943
NEW '2038-01-19 12:13:14.123': 5.314
```
This is probably as fast as we can go without turning this into a C extension. Slowest part seems to be casting to `int` right now.

Increase performance when casting dates

---

_mysql.c
tests/test_MySQLdb_capabilities.py

Thanks for mysqlclient. :-) When working with Django 1.8 (Python 3.4) with a legacy database containing spatial fields in MySQL 5.5, I got an UnicodeDecodeError as soon as trying to access (read) something from tables containing spatial fields. When tracking down the problem I found that the exception was raised in the mysqlclient module. So I added a small test case and voila - same exception here.
So either I (or Django) are not using your module correctly, or there is a bug.
In case you want me to look closer at the problem I'm willing to do so - however, I think you know your code better than I do and would be much faster when finding out what's going on.

Added test for MULTIPOLYGON (that fails in 1742946)

---

INSTALL
setup_posix.py

When using MySQL from oracle, `libmysqlclient.so` may not be in `/etc/ld.so.conf`.
You can put `rpath` to `mysql_config`, but current mysqlclient-python doesn't pass it to linker.

Pass options in `mysql_config --libs` to `extra_linker_args`

---

.travis.yml
MySQLdb/cursors.py
_mysql.c
tests/configdb.py
tests/test_MySQLdb_dbapi20.py
tests/test_MySQLdb_nonstandard.py
tox.ini

Don't fetch warnings when there is next result

---

MySQLdb/cursors.py

When committing to a mysql database, warnings came up as a TypeError in Python 3.5:
"TypeError: cannot use a string pattern on a bytes-like object"
The "warn" library is expecting string objects, but these warnings in Python 3.5 were being passed as byte strings. I added a conditional to decode any warnings that come through as byte strings to prevent a TypeError surfacing when warnings are present.

Fixing Python 3.5 Compatibility with Bytes to Strings for Stddout

---

README.md

As per their email ‘Changes to project subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.

Convert readthedocs link for their .org -> .io migration for hosted projects

---

MySQLdb/cursors.py

Hi, I've got  'surrogates not allowed' error when I put unicode string into stored procedure's argument.
This is pr for the issue.
cf: https://github.com/PyMySQL/mysqlclient-python/issues/90 .

unicode string in argument of string raises error

---

MySQLdb/cursors.py
tests/test_MySQLdb_capabilities.py

Added `surrogateescape` encoding option and modify current test case for this situation.

add surrogate escape for callproc and test case for that

---

MySQLdb/cursors.py
tests/test_MySQLdb_capabilities.py

Dear MySQLdb team,
Here are a couple of suggestions regarding warnings issued by the library:
1. _Include error code in warnings, not just string_  
I thought it would make sense for the `Warning` instances to not just have a string argument but, same as with errors, to also include the error code (as first argument, with string being second).
2. _Fix warning propagation for unbuffered queries_  
`db.warning_count()` was called during `nextset()`. However, for unbuffered queries, the warning count is not available until the whole result has been fetched. By instead calling `db.warning_count()` later via `_warning_check` instead (which work as `_defer_warnings` is set), warnings are always received.

Warning propagation improvements

---

_mysql.c

While it's MYSQL_VERSION_ID is 50706 and MySQL 5.7.6 has it.
Since MySQL 5.7.6 is old milestone version, just drop supporting it.
fixes #110

MySQL Connector/C 6.1.6 doesn't have mysql_real_escape_string_quote

---

MySQLdb/__init__.py
MySQLdb/connections.py

[PyMySQL](https://github.com/PyMySQL/PyMySQL) already does this via `escape_bytes()` [converters.py](https://github.com/PyMySQL/PyMySQL/blob/master/pymysql/converters.py). For compatibility maybe this is a good idea? (I think this would behave the same as with PyMySQL in that nothing it only affects bytes~~/bytearray~~ + Python 3 and bytearray for both versions.)
I think it's not possible to add to `Connection.encoders` (via constructor) because e.g. `self.encoders[bytes]` is overridden **after** the `conv` argument is parsed.

Use _binary prefix for bytes/bytearray parameters

---

MySQLdb/__init__.py
MySQLdb/connections.py

Reverts PyMySQL/mysqlclient-python#106

Revert "Use _binary prefix for bytes/bytearray parameters" (#106)

---

README.md

Im trying this in my mac, and work! 
Hope this help

adding requirement for Mac OS

---

MySQLdb/__init__.py
MySQLdb/connections.py
tests/test_MySQLdb_capabilities.py

This should hopefully address the problems of the previous attempt (#106, #123). An optional connection parameter is used to enable the behaviour. I've also added a unit test to check expected query parameter handling.

Use _binary prefix for bytes/bytearray parameters (now optional)

---

MySQLdb/connections.py

I want to change the API to close connection.

deprecate Connection.__enter__

---

_mysql.c

fix leak of connection->converter.

---

MySQLdb/connections.py

This produced the error `TypeError: _tuple_literal() missing 1 required positional argument: 'd'` on line 316. Introduced in commit https://github.com/PyMySQL/mysqlclient-python/commit/ca4317a6b5ffc4c78c711123b52dfda400d00eb5, release [1.3.11](https://github.com/PyMySQL/mysqlclient-python/releases/tag/1.3.11).

Remove unused parameter from method definition

---

MySQLdb/connections.py
tests/test_MySQLdb_capabilities.py

When using use_unicode, results from tiny/medium/long blobs were not converted correctly.

Tiny/medium/long blobs are not converted correctly, MULTIPOLYGON test suite was checking against wrong value

---

README.md
setup_posix.py

resolves #189, #175, #170, #169, etc.

resolve string index out of range errors

---

MySQLdb/cursors.py

(Equivalent of https://github.com/PyMySQL/PyMySQL/pull/636, for this module.)
Rather than making an individual SET query for each and every parameter specified for a callproc call, use one single call instead, saving round-trip time (if one has more than one parameter). This can be significant if one is making many repeated callproc calls which have multiple arguments.
Then only downside I can think of is that if one or more arguments are quite large, combining them all could hit the max_allowed_packet limit. However, if it is only e.g. one large argument this will make next to no difference and the user should have an increased max_allowed_packet value in anticipation of e.g. larger blobs already.

Reduce callproc roundtrip time

---

setup_posix.py

On ubuntu 16, and possibly newer, this error occurs when
doing a static build.
undefined symbol: _ZTVN10__cxxabiv117__class_type_infoE
Add -lstdc++ to the libraries to resolve.  Code remains
functional under older versions.

resolve a missing symbol error under ubuntu 16

---

MySQLdb/converters.py
tests/capabilities.py

IEEE 754 double needs to be formatted with 17 decimal digits to guarantee lossless round-trip.
So this doesn't work currently:
```
In [125]: import MySQLdb
In [126]: con = MySQLdb.connect()
In [127]: cursor = con.cursor()
In [128]: val = 18014398509481982.
In [129]: val
Out[129]: 1.8014398509481982e+16
In [130]: cursor.execute("SELECT %s", (val,))
Out[130]: 1
In [131]: result = cursor.fetchone()[0]
In [132]: result
Out[132]: 1.8014398509482e+16
In [133]: result == val
Out[133]: False
```

Fixed float adapter.

---

MySQLdb/converters.py
tests/capabilities.py

Without it MySQL treats`Decimal`s like `float`s .

Added Decimal adapter.

---

doc/user_guide.rst

Currently `CursorDictRowsMixIn` is displayed differently from adjacent items:

Fix some formatting and typo in user_guide.rst.

---

MySQLdb/cursors.py

Clear cursor._query before query()

---

_mysql.c

libmysqlclient returns CR_SERVER_GONE_ERROR(2006) when using
closed connection.  But libmariadbclient cause SEGV.
For compatibility, emulate CR_SERVER_GONE_ERROR manually.
Ref: GH-270

Return OperationalError for closed connection

---

MySQLdb/converters.py
tests/capabilities.py

Converter for `Decimal` implemented in #267 doesn't handle of `Decimal`s with exponent:
```
In [7]: str(Decimal('1e1'))
Out[7]: '1E+1'
```
This PR makes it to be formatted in the other way:
```
In [16]: format(Decimal('1e1'), 'f')
Out[16]: '10'
```
It seems that it's not documented well how `Decimal.__format__()` works (https://bugs.python.org/issue23460 could be related), and I found this formatting in [python-list](https://mail.python.org/pipermail/python-list/2009-December/562330.html).
@methane, apologies for not handling this at once.

Fix conversion of decimals with exponent.

---

MySQLdb/_mysql.c
tests/test_MySQLdb_nonstandard.py

Add a fileno() method to _mysql.connection. This permits low-level access to the
underlying network connection. My specific usecase for this is wanting to tweak
the TCP timeout (TCP_USER_TIMEOUT).

Expose the file descriptor of the underlying libmysqlclient connection.

---

MySQLdb/_mysql.c
MySQLdb/connections.py
MySQLdb/converters.py
MySQLdb/cursors.py
MySQLdb/times.py

It was workaround for `bytes %`.
Since we dropped Python 3.4 support, we can use just `bytes %` now.

Stop using surrogate escape.

---

MySQLdb/_exceptions.py
MySQLdb/_mysql.c
MySQLdb/_mysql_exceptions.py
MySQLdb/compat.py
MySQLdb/connections.py
MySQLdb/converters.py
MySQLdb/cursors.py
doc/_exceptions.rst
doc/_mysql.rst
doc/user_guide.rst
metadata.cfg

Raise ProgrammingError for nan and inf

---

MySQLdb/connections.py
MySQLdb/cursors.py

Django touched private area of this library.
Removing unused variables broke Django.
While Django 2.0 fixed it, Django 1.11 LTS doesn't fix it
because Django 1.11 is in security-only fix mode.
So add unused variables for Django 1.11 compatibility.
They will be removed in 1.5.
Fix #303, #306

Add some garbage for Django 1.11 compatibility

---

HISTORY.rst

I looked into the related issues and think that the description is quite misleading or may be wrong.

Fix description of SEGV issue in HISTORY

---

MySQLdb/connections.py

Hi, this pull request aims for improving documents for `Connection` class arguments `use_unicode` and `charset`:
- Removing redundant words in `use_unicode`
- Add more explanation for these two args. I think we should tell developers why `use_unicode` is set to False on Python 2 and True on Python 3 by default, and the fact that `charset` does not imply `use_unicode` but changes its default value. The world `implies` might be misleading for developers who did not see the code. 
OT I noticed that the upstream project https://github.com/farcepest/MySQLdb1 hasn't been updated for a long time(maybe not in maintenance, sad), so I decided to pull request here :)

Improve documents for `Connection` class arguments `use_unicode` and `charset`

---

MySQLdb/_mysql.c

when callback conversion is used the value is always passed as Str. 
Missing break; 
Turns out this was just reported. #343

Bug in _mysql_field_to_python

---

MySQLdb/_mysql.c

Looking at mysql_real_connect on failure it does not free the memory of the passed in MYSQL* struct. only mysql_close does that.
So we can't set open=0 after we mysql_init or dealloc will not cleanup the memory.
Also if mysql_init returns NULL we are out of memory and shouldn't set open=1, or we could segfault in dealloc if we didn't seg before that.

memory leak in ConnectionObject_Initialize when mysql_real_connect fails

---

setup_posix.py

I want to build a statically-linked, binary wheel for the debian stretch-based docker image `python:3.6.8-slim` (so I don't need to install libmysqlclient-dev on all my images)
Example Dockerfile:
```
FROM python:3.6.8-slim as build-mysqlclient
RUN apt update && apt install -y build-essential default-libmysqlclient-dev git
RUN git clone https://github.com/PyMySQL/mysqlclient-python
WORKDIR /mysqlclient-python
RUN python setup.py --static bdist_wheel
```
The above Dockerfile gives this error:
```
Step 5/5 : RUN python setup.py --static bdist_wheel
---> Running in 1e8aabf66608
Traceback (most recent call last):
File "setup.py", line 16, in <module>
metadata, options = get_config()
File "/mysqlclient-python/setup_posix.py", line 81, in get_config
raise ValueError("Couldn't identify mysql …
```

Fix error building with --static on debian stretch docker image due to mariadb client name

---

MySQLdb/_mysql.c

fixes #367
ref: https://jira.mariadb.org/browse/MDEV-20116

call mysql_library_init in module initialization

---

MySQLdb/_mysql.c
MySQLdb/connections.py

A trivial change to allow for setting the authentication plugin used when connecting to mysql.
The `auth_plugin` parameter is the same parameter name used by mysql-connector-python and seemed sensible.

Add support to change the authentication plugin (MYSQL_DEFAULT_AUTH)

---

MySQLdb/_mysql.c

Two members of the main MYSQL structure are incorrectly defined as unsigned integers rather than unsigned longs in a PyMemberDef declaration. This can result in incorrect values being returned (I found this on SPARC, where client_flag attribute was always zero).
For reference, here is the declaration in the MySQL code (same for 5.5, 5.6, 5.7 and 8.0):
https://github.com/mysql/mysql-server/blob/5.7/include/mysql.h#L287

fix PyMemberDef type of two attributes

---

MySQLdb/_mysql.c
MySQLdb/connections.py

Use cp1252 for latin1 charset

---

README.md

they made this change in https://github.com/Homebrew/homebrew-core/pull/46566
I verify that clear install `mysql-client` , version `8.0.18`
the `libs="$libs -lmysqlclient -lssl -lcrypto"` issue has been fixed.
so change the `README.md` to reflect the new change

homebrew migrates mysql-connector-c to mysql-client

---

MySQLdb/_mysql.c

Users of gc.get_referrers() could cause a SystemError to be raised if this function is running in a different python thread.
We ended up doing this at Facebook just to be safe, because it was really hard figuring out that it was not a _mysql issue but usage of gc.get_referrers() in a multi-threaded environment. but I understand if you don't feel its needed.

Add some gc safety around _mysql__fetch_row

---

.travis.yml
MySQLdb/_mysql.c

It is unsafe.
Fixes #435.
See also #348.

Don't use PyTuple_Resize

---

doc/user_guide.rst

This change updates the documentation for `Cursor`, since it does not use `CursorWarningMixIn` anymore.

Update the documentation for `Cursor`

---

.github/workflows/windows.yaml

Updated GitHub Actions to include Python 3.9 build on Windows.
Updated MariaDB Connector C to the latest version (3.1.11), which includes several bugfixes and support for TLS v1.3

GitHub Action with Python 3.9 and MariaDB Connector C 3.1.11

---

.github/workflows/windows.yaml

Updated build workflow to work with branches, as well - which is of course helpful for development and debugging.
Fixed the cache key to make use of the CONNECTOR_VERSION environment variable. Previously it used 'mariadb-connector-${CONNECTOR_VERSION}-win' literally, as the variable was never substituted.
Reverted back to connector 3.1.9, as newer versions result in link error. This was previously undiscovered due to the cache key issue.

GitHub Actions workflow updated and caching fixed, Revert back to MariaDB Connector C 3.1.9

---

MySQLdb/connections.py
tests/test_connection.py

Disabling multi statements can help protect against SQL injection attacks.

Let multi statements be optional

---

MySQLdb/connections.py

Fixes #489 
Seems this may have just been missed in https://github.com/PyMySQL/mysqlclient/pull/411

Remove bytes encoder that was specifically for Django 1.11

---

doc/user_guide.rst

As a follow up to fa25358d0f171bd8a63729c5a8d76528f4ae74e9 also change the remnants of `passwd` and `db` in the user documentation.

update remnants of passwd and db also in docs

---

README.md
setup_windows.py
site.cfg

I know that you are not a Windows user and that you don't wish to provide support for source builds on Windows. However, I am a Windows user and have had to build mysqlclient from source because you do not provide wheels for 32-bit versions of Python (which I need for other reasons). I am hoping that you will accept this PR that should make it easier for users like me to be able to install mysqlclient from source without needing to clone this repo to edit site.cfg and setup_windows.py.
I know this cannot account for all possible setups, but at least with these changes it has a chance of building under some setups, which should be an improvement on the current defaults in setup_windows.py and site.cfg which I don't believe have any chance at building correctly. This PR includes 5 small …

Better support for building on Windows

---

tests/test_MySQLdb_capabilities.py

Use utf8mb4 in test_binary_prefix

Fix tests with MySQL 8.0

---

MySQLdb/_exceptions.py

Add __module__ attributes to exception classes.

---

tests/dbapi20.py

There is a small typo in tests/dbapi20.py.
Should read `portable` rather than `portible`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, portible -> portable

---

setup.py

In https://github.com/PyMySQL/mysqlclient/commit/684dcbf0657f18c1ba12fe21732323c890ff20ab and https://github.com/PyMySQL/mysqlclient/commit/dac24e7b05b83eb1511e25e3cd8f8c20b7fbe112 it looks like Python 3.6 support has been dropped. This change updates `python_requires` to match so tools like `pip` know not to install the next version in a Python 3.6 environment.

Update python_requires to match supported python versions

---

MySQLdb/converters.py

Ref: https://github.com/PyMySQL/PyMySQL/pull/1067

Raise ProgrammingError on -inf

---

MySQLdb/_mysql.c
tests/capabilities.py
tests/test_MySQLdb_capabilities.py
tests/test_errors.py

ER_BAD_NULL should be IntegrityError.

---

README.md
metadata.cfg
setup_common.py
setup_posix.py
setup_windows.py
site.cfg

MySQL breaks mysql_config often. Use pkg-config instead.
Fixes #584

Use pkg-config instead of mysql_config

---

.github/workflows/tests.yaml
MySQLdb/connections.py
doc/user_guide.rst
tests/test_MySQLdb_nonstandard.py

Fixes #563 
This change does not affect existing behavior if the `collate` option is not specified.
To test this out locally, e.g. in a Django project:
* Make sure you have MySQL or MariaDB C connector, and a C compiler installed.
* `pip install git+https://github.com/vsalvino/mysqlclient.git`
* Set your database connection as so:
```python
DATABASES = {
"default": {
"ENGINE": "django.db.backends.mysql",
"HOST": "",
"NAME": "",
"USER": "",
"PASSWORD": "",
"OPTIONS": {
"charset": "utf8mb4",
"collation": "utf8mb4_unicode_ci",
},
}
}
```

Add collation option

---

MySQLdb/__init__.py

The current expection handling is too vague, and in certain circumstances, the error message may confuse the user.
For example, if an error occurs while importing the "_mysql" module, the original error message is as follows:
```
File "MySQLdb/__init__.py", line 18, in <module>
from . import _mysql
ImportError: /lib64/libstdc++.so.6: cannot allocate memory in static TLS block
```
But on the user side, he can only see the exception message like this: 
```
/MySQLdb/__init__.py", line 24, in <module>
version_info, _mysql.version_info, _mysql.__file__
NameError: name '_mysql' is not defined
```
This PR fixes this issue by making the exception handling statements more precise.

Improved exception handling when importing the module

---

src/MySQLdb/_mysql.c
src/MySQLdb/cursors.py
tests/test_cursor.py

Discard results without converting them into Python objects.

---

doc/MySQLdb.rst
doc/conf.py
src/MySQLdb/cursors.py

Fix sphinx warnings

---

src/MySQLdb/cursors.py
tests/default.cnf
tests/test_cursor.py

Fix executemany with binary prefix

---

src/MySQLdb/_mysql.c

After aed1dd2, Connection.escape() used ASCII to escape Unicode input.
This commit makes it uses connection encoding instead.

Fix Connection.escape() with Unicode input

---

src/MySQLdb/_mysql.c

We are trying to use SSL with MariaDB and ran into the issue with `ssl_mode` (fixed by the recently merged #475). We tried installing the latest commit on `main` and it produces the following error when building:
```shell
running build_ext
building 'MySQLdb._mysql' extension
creating build/temp.linux-aarch64-cpython-310
creating build/temp.linux-aarch64-cpython-310/src
creating build/temp.linux-aarch64-cpython-310/src/MySQLdb
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC "-Dversion_info=(2, 2, 0, 'dev', 0)" -D__version__=2.2.0.dev0 -I/usr/local/include/python3.10 -c src/MySQLdb/_mysql.c -o build/temp.linux-aarch64-cpython-310/src/MySQLdb/_mysql.o -I/usr/include/mariadb/ -std=c99
In file included from /usr/local/include/python3.10/Python.h:8,
from …
```

fix: fix sslmode typo

---

README.md

Add build dependency for `pkg-config` to documentation

---

src/MySQLdb/_mysql.c
src/MySQLdb/connections.py

MySQL 8.0.33+ shows deprecation warning to stderr.
So we avoid using it as possible.
In the future, we will deprecate `reconnect` option of the `Connection.ping()`.

Do not use MYSQL_OPT_RECONNECT as possible.

---

README.md

Verified exhaustiveness thanks to:
```bash
grep -r '```' --include=*.md
```

add bash syntax highlighting to `README.md`

---

README.md

homebrew's prefix can vary - with this minor change, the pkgconfig path should work in more user environments.

docs: Improve portability of brew prefix

---

src/MySQLdb/_mysql.c
src/MySQLdb/connections.py

MySQL use ssl by default but MariaDB don't.
Until mysqlclient<=2.2.1, `ssl=True` unintentionally allowed and it called `mysql_ssl_set(mysql, NULL, NULL, NULL, NULL, NULL)`. Although it is no-op in MySQL Connector, MariaDB Connector silently set MYSQL_OPT_SSL_ENFORCE when the API is called. (See #698)
In case of PyMySQL, ssl is not used by default but `ssl=True` behave like `sslmode="PREFERRED"`.
For better backward compatibility and compatibility with PyMySQL and security, I decided to allow ssl=True and it means sslmode="REQUIRED" on MySQL Connector and
set MYSQL_OPT_SSL_ENFORCE on MariaDB Connector.
Fix #699

Support `ssl=True`

---

setup.py

After #584, pkg-config is required. 
I use Percona Server for MySQL, and use both the server as well as their client library. Percona Server for MySQL began shipping a .pc file in https://github.com/percona/percona-server/pull/5215 Percona Server for MySQL 8.0.37, but the library name they ship is `perconaserverclient`:
```
$ pkg-config --exists perconaserverclient
$ echo $?
0
$ pkg-config --cflags perconaserverclient
-I/usr/include/mysql
$ pkg-config --libs perconaserverclient
-lperconaserverclient
```
This PR adds support for that name to pkg-config invocations.

Support building against Percona Server builds of MySQL client library `libperconaserverclient`

---

README.md
doc/user_guide.rst

Suggest to add MariaDB to README and documentation intro as mentioned in https://github.com/PyMySQL/mysqlclient/issues/719 - hope this is ok?

add MariaDB to README and doc

---

doc/user_guide.rst
src/MySQLdb/_mysql.c
src/MySQLdb/connections.py

support server_public_key_path option.

---

setup.py

*MariaDB 11.4.4* (from *.zip* file) header files are located under `${MYSQLCLIENT_CONNECTOR}/include/mysql`.<br>
Don't know how it was in previous versions, but without the above path in include list the *C* source file fails to compile.

MariaDB include paths for Win

---

src/MySQLdb/connections.py

This change will add `self.database` as the Connection attribute displaying the database name from connection parameters.
I've described the reason for this change in https://github.com/PyMySQL/mysqlclient/discussions/751 . Moreover, I believe that this attribute can be useful for other use-case where the info about the database name can be useful.

add database name as the Connection attribute

---

doc/user_guide.rst
src/MySQLdb/_mysql.c
src/MySQLdb/connections.py

Adds support for `MYSQL_OPT_LOAD_DATA_LOCAL_DIR` in `mysql_options()` as the kwarg `local_infile_dir`. A bit safer alternative than `local_infile` for MySQL versions >= 8.0.21.
(P.S. I'm a bit out of my depth with this PR but tried my best following the example of a previous PR with a similar addition, if there is anything that needs changing I'm happy to do it.)
Thank you for reviewing!

support local_infile_dir option
